name: check-pr

on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
      - reopened
      - synchronize

permissions:
  pull-requests: read

jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@c24d6dd07c69e0826c52021944f216b2e3192535 # v5.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
