name: check-code

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  kics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Scan Repository
        uses: checkmarx/kics-github-action@aacf8e81cd48e227259c937c215b352e02ad447a # v2.1.0
        with:
          disable_secrets: true
          enable_comments: true
          ignore_on_exit: results
          output_formats: "json,sarif"
          output_path: reports
          path: .
