name: check-md

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Link Checker
        uses: lycheeverse/lychee-action@7da8ec1fc4e01b5a12062ac6c589c10a4ce70d67 # v2.0.0
        with:
          args: --exclude '(app|support).harness.io' --no-progress --verbose './**/*.md'
          fail: true
