name: check-code

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  kics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Scan Repository
        uses: checkmarx/kics-github-action@d1b692d84c536f4e8696954ce7aab6818f95f5bc # v2.0.0
        with:
          disable_secrets: true
          enable_comments: true
          ignore_on_exit: results
          output_formats: "json,sarif"
          output_path: reports
          path: .
