name: check-code

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  kics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Scan Repository
        uses: checkmarx/kics-github-action@8a44970e3d2eca668be41abe9d4e06709c3b3609 # v1.7.0
        with:
          disable_secrets: true
          enable_comments: true
          ignore_on_exit: results
          output_formats: "json,sarif"
          output_path: reports
          path: .
