name: check-code

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  kics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Scan Repository
        uses: checkmarx/kics-github-action@94469746ec2c43de89a42fb9d2a80070f5d25b16 # v2.1.3
        with:
          disable_secrets: true
          enable_comments: true
          ignore_on_exit: results
          output_formats: "json,sarif"
          output_path: reports
          path: .
