name: check-md

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Link Checker
        uses: lycheeverse/lychee-action@f613c4a64e50d792e0b31ec34bbcbba12263c6a6 # v2.3.0
        with:
          args: --exclude '(app|support).harness.io' --no-progress --verbose './**/*.md'
          fail: true
