name: check-code

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  kics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Scan Repository
        uses: checkmarx/kics-github-action@252e73959bd4809a14863cbfbb42d7a90d5a4860 # v2.1.1
        with:
          disable_secrets: true
          enable_comments: true
          ignore_on_exit: results
          output_formats: "json,sarif"
          output_path: reports
          path: .
